// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuEgYExJhw8-FVXWgzQY3zBkR9Xw_a4Wk',
    appId: '1:324880859336:web:c43eebb404f9f8648b65fd',
    messagingSenderId: '324880859336',
    projectId: 'vision-screener',
    authDomain: 'vision-screener.firebaseapp.com',
    storageBucket: 'vision-screener.firebasestorage.app',
    measurementId: 'G-WQBZNZ3D42',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAowL5W2q2VtRoisXUJrHBDxLjjz3YRLYg',
    appId: '1:324880859336:ios:85d2d24c749b2b858b65fd',
    messagingSenderId: '324880859336',
    projectId: 'vision-screener',
    storageBucket: 'vision-screener.firebasestorage.app',
    androidClientId: '324880859336-12penkcnop47g8fe14mroa4rt3moqep9.apps.googleusercontent.com',
    iosClientId: '324880859336-02no2ucr7v44jqctf7n7agsdo393i1mv.apps.googleusercontent.com',
    iosBundleId: 'com.example.eyesightFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAowL5W2q2VtRoisXUJrHBDxLjjz3YRLYg',
    appId: '1:324880859336:ios:85d2d24c749b2b858b65fd',
    messagingSenderId: '324880859336',
    projectId: 'vision-screener',
    storageBucket: 'vision-screener.firebasestorage.app',
    androidClientId: '324880859336-12penkcnop47g8fe14mroa4rt3moqep9.apps.googleusercontent.com',
    iosClientId: '324880859336-02no2ucr7v44jqctf7n7agsdo393i1mv.apps.googleusercontent.com',
    iosBundleId: 'com.example.eyesightFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuEgYExJhw8-FVXWgzQY3zBkR9Xw_a4Wk',
    appId: '1:324880859336:web:fc354ce896f9fd558b65fd',
    messagingSenderId: '324880859336',
    projectId: 'vision-screener',
    authDomain: 'vision-screener.firebaseapp.com',
    storageBucket: 'vision-screener.firebasestorage.app',
    measurementId: 'G-8GPHCL98VD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcpGwunaFERVa90zu_T58_NckTNbU6ruU',
    appId: '1:324880859336:android:ce6c40da6ddb13708b65fd',
    messagingSenderId: '324880859336',
    projectId: 'vision-screener',
    storageBucket: 'vision-screener.firebasestorage.app',
  );

}