org.gradle.jvmargs=-Xmx4g -Dkotlin.daemon.jvm.options=-Xmx2g -XX:+HeapDumpOnOutOfMemoryError
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true


# === AndroidX / Jetifier ===
android.useAndroidX=true
android.enableJetifier=false

# === Flutter/SDK versions (keep these consistent with app/build.gradle) ===
flutter.minSdkVersion=26
android.minSdkVersion=26